site_name: NIE Lab Guide
site_description: The Lab guide for all practice labs at NIE. Sharpen your skills with these exercises spanning networking, Microsoft, and general IT skills!
site_author: Network It Easy

theme:
  name: material
  favicon: /img/favicon.ico
  logo: /img/logo.png
  features:
    - navigation.top  # Enables top navigation
    - navigation.tabs # Adds tabs for better organization
    - navigation.footer # Enables previous/next page navigation
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - macros
  - glightbox:
      zoomable: true
      shadow: true
nav:
  - Home: index.md
  - Labs:
      - Networking:
          - Lab Overview: labs/networking/lab-overview.md
          - Network Information: labs/networking/network-info.md
          - Lab 1 - Configure Cisco Switch: labs/networking/cisco-switch-setup.md
          - Lab 2 - Adding Devices to Network: labs/networking/add-devices-to-network.md
          - Lab 3 - Configure WatchGuard Firewall: labs/networking/watchguard-firewall-setup.md
          - Lab 4 - Putting It All Together: labs/networking/lab-putting-it-all-together.md
          - Practice Tests:
            - WatchGuard Network & Security Exam: labs/networking/practice-tests/wg-network-security-test.md
      - Azure:
          - Azure Lab Info: labs/azure/azure_lab1.md
  - Lab Calendar: calendar.md
  - Feedback: feedback.md
extra:
  office:
    location: 5400 Patton Dr. STE 4a, Lisle, Illinois 60532
    contact: support@networkiteasy.com
  vlans:
    lan:
      name: "LAN"
      id: 1
      subnet: "192.168.10.0/24"
      subnet_mask: "255.255.255.0"
      cidr: /24
      dhcp_range: "192.168.10.20 - .254"
      dhcp_server: "DC01"
      gateway: "192.168.10.1"
      description: "Main Office Data VLAN"
      domain_name: nielab.local
    security:
      name: "SECURITY"
      id: 20
      subnet: "192.168.20.0/24"
      subnet_mask: "255.255.255.0"
      cidr: /24
      dhcp_range: "192.168.20.50 - .254"
      dhcp_server: "Firewall"
      gateway: "192.168.20.1"
      description: "Security devices (Cameras, NVR, Building Access Controls)"
    voip:
      name: "VOIP"
      id: 30
      subnet: "192.168.30.0/24"
      subnet_mask: "255.255.255.0"
      cidr: /24
      dhcp_range: "192.168.30.50 - .253"
      dhcp_server: "Allworx Server"
      gateway: "192.168.30.1"
      description: "IP phones and voice-related services"
    guest:
      name: "GUEST"
      id: 40
      subnet: "192.168.40.0/26"
      subnet_mask: "255.255.255.192"
      cidr: /26
      dhcp_range: "192.168.40.10 - .62"
      dhcp_server: "Firewall"
      gateway: "192.168.40.1"
      description: "Isolated guest network"
  devices:
    cisco_switch:
      name: "SW01"
      type: "Cisco SG350X 24 Port Switch"
      ip: "192.168.10.2"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      default_user: "cisco"
      default_pass: "cisco"
      default_ip: "192.168.1.254"
      custom_user: "nie"
      custom_pass: "$ecureLab!"
      description: "Cisco SG350X 24 Port Switch"
      banner: "NIE 24-Port Cisco Lab Switch"
      mac: "40:A6:E8:EF:D0:EC"
    aruba_switch:
      name: "SW02"
      type: "Aruba 1930 Instant On 24 Port Switch"
      ip: "192.168.10.3"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      description: "Aruba 1930 Instant On 24 Port Switch"
      mac: "D4:E0:53:7B:38:A2"
    ap01:
      name: "AP01"
      type: "Aruba Instant On AP22"
      ip: "192.168.10.5"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      description: "Aruba AP22 Instant On Access Point"
      mac: "60:26:EF:CB:E6:CE"
    dc01:
      name: "DC01"
      type: "Windows Server"
      ip: "192.168.10.10"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      description: "Windows Server 2022 running Active Directory."
    allworx:
      name: "Allworx"
      type: "Allworx Server"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      ip: "192.168.30.254"
      vlan: "VOIP"
      description: "Allworx Verge XXXX Server. Allows for a full-fledged on-prem VoIP system."
    firewall:
      name: "NIE-LAB-T45-PAX8"
      type: "WatchGuard T45 Firewall"
      ip: "192.168.10.1"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      description: "WatchGuard T45 Firewall."
      model: "T45"
      default_ip: "10.0.1.1"
      default_web_address: "https://10.0.1.1:8080"
      default_subnet: 10.0.1.0/24
      default_status_account: "status/readonly"
      default_admin_account: "admin/readwrite" 
      software_download: https://software.watchguard.com/SoftwareDownloads?current=true&familyId=a2R6S00000537cVUAQ
      custom_status_account: "status/$ecureLab@"
      custom_admin_account: "admin/$ecureLab!"
    pc01:
      name: PC01
      mac: E4:54:E8:51:60:13
      description: Dell OptiPlex 3080 used for testing connections.
      type: Dell OptiPlex 3080
      user_account: "LabUser / $ecureLab!"
      custom_user: LabUser
      custom_pass: $ecureLab!
  wan:
    ip: "96.81.211.76"
    subnet_mask: "255.255.255.240"
    cidr: /28
    gateway: "96.81.211.78" 
  urls:
    feedback_webhook: "https://engine.rewst.io/webhooks/custom/trigger/01946b93-eb43-7a50-8d4d-fcc366deaa30/cb4b611f-612d-4c1d-951f-79aa3fefeafd"
    lab_files: "https://networkiteasy-my.sharepoint.com/:f:/p/dustin_l/EmBaZ0lvBzlMtdxgWilxVREBBPFPR-y7WOJizvE92L4CRA?e=cPRhYn"
  palette:
    primary: deep purple
    accent: cyan
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
extra_javascript:
  - https://alcdn.msauth.net/browser/2.25.0/js/msal-browser.min.js  # MSAL.js library
  - js/open_links_in_new_tab.js  # JS to opene xternal links in new tab
  - js/msal.js  # MSAL logic for Entra Authentication
