site_name: Internal Lab Guide
site_description: A guide for practice labs within NIE.
site_author: Network It Easy
theme:
  name: material
  features:
    - navigation.top  # Enables top navigation
    - navigation.tabs # Adds tabs for better organization
plugins:
  - search
  - macros
nav:
  - Home: index.md
  - Labs:
      - Networking:
          - Lab Overview: labs/networking/lab_overview.md
          - Network Details: labs/networking/lab_info.md
          - Lab 1 - Configure Cisco Switch: labs/networking/lab1.md
          - Lab 2: labs/networking/lab2.md
          - Lab 3: labs/networking/lab3.md
      - Azure:
          - Azure Lab Info: labs/azure/azure_lab1.md

extra:
  vlans:
    lan:
      name: "LAN"
      id: 1
      subnet: "192.168.10.0/24"
      dhcp_range: "192.168.10.10 - .254"
      dhcp_server: "DC01"
      gateway: "192.168.10.1"
      description: "Main Office Data VLAN"
    security:
      name: "SECURITY"
      id: 20
      subnet: "192.168.20.0/24"
      dhcp_range: "192.168.20.50 - .254"
      dhcp_server: "Firewall"
      gateway: "192.168.20.1"
      description: "Security devices (Cameras, NVR, Building Access Controls)"
    voip:
      name: "VOIP"
      id: 30
      subnet: "192.168.30.0/24"
      dhcp_range: "192.168.30.50 - .253"
      dhcp_server: "Allworx Server"
      gateway: "192.168.30.1"
      description: "IP phones and voice-related services"
    guest:
      name: "GUEST"
      id: 40
      subnet: "192.168.40.0/26"
      dhcp_range: "192.168.40.10 - .62"
      dhcp_server: "Firewall"
      gateway: "192.168.40.1"
      description: "Isolated guest network"
  devices:
    cisco_switch:
      name: "SW01"
      type: "Cisco SG350X 24 Port Switch"
      ip: "192.168.10.2"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      default_user: "cisco"
      default_pass: "cisco"
      custom_user: "nie"
      custom_pass: "pass123!"
      description: "Cisco SG350X 24 Port Switch"
      banner: "NIE 24-Port Cisco Lab Switch"
    aruba_switch:
      name: "SW02"
      type: "Aruba 1930 Instant On 24 Port Switch"
      ip: "192.168.10.3"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      description: "Aruba 1930 Instant On 24 Port Switch"
    ap01:
      name: "AP01"
      type: "Aruba Instant On AP22"
      ip: "192.168.10.5"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      description: "Aruba AP22 Instant On Access Point"
      mac: 60:26:EF:CB:E6:CE
    dc01:
      name: "DC01"
      type: "Windows Server"
      ip: "192.168.10.10"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      description: "Windows Server 2022 running Active Directory."
    allworx:
      name: "Allworx"
      type: "Allworx Server"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      ip: "192.168.30.254"
      vlan: "VOIP"
      description: "Allworx Verge XXXX Server. Allows for a full-fledged on-prem VoIP system."
    firewall:
      name: "NIE-LAB-T45-PAX8"
      type: "WatchGuard T45 Firewall"
      ip: "192.168.10.1"
      subnet_mask: "255.255.255.0"
      cidr: "/24"
      vlan: "LAN"
      description: "WatchGuard T45 Firewall."
      model: "T45"
  social:
  palette:
    primary: deep purple
    accent: cyan
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
extra_javascript:
  - js/open_links_in_new_tab.js  # Include custom JavaScript file to force external links to open in New Tabs throughout docs
