site_name: Internal Lab Guide
site_description: A guide for practice labs within NIE.
site_author: Network It Easy
theme:
  name: material
nav:
  - Home: index.md
  - Labs:
      - Overview: labs/networking/overview.md
      - Lab Info: labs/networking/lab_info.md
      - Networking:
          - Lab 1: labs/networking/lab1.md
          - Lab 2: labs/networking/lab2.md
          - Lab 3: labs/networking/lab3.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nie-git/nie-labs-mkdocs
  palette:
    primary: deep purple
    accent: cyan
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
